"""
scripts/precompute_latents.py
==============================
Precomputes a full 64^3x4 VAE latent for every cached patient, ONCE, via sliding-window
encoding. See src/data/sliding_window.py's module docstring for why this can't just be
`vae.encode(full_256_cubed_volume)`: the first encoder conv alone needs ~54GB of workspace at
full 256^3 resolution (same figure that forced patch-based VAE *training* in the first
place -- see src/data/lidc_dataset.py's module docstring), which no 8GB dev card can hold.

Instead this slides the already-proven-safe 96^3 patch size across the full volume with
overlap, encodes each window separately (this is exactly what VAE training already does per
step, just exhaustively over the whole volume instead of one random crop), and blends the
overlapping 24^3 latent outputs with sliding_window_average's tapered weights so patch
boundaries don't leave seams in the stitched 64^3 result.

This is a ONE-TIME cost per patient, not a per-training-step cost -- the whole point, since
diffusion training runs for 500k steps and re-encoding on the fly every step would be
enormously wasteful even where it fit in memory.

Usage:
    python -m scripts.precompute_latents \
        --checkpoint checkpoints/vae/vae_epoch0084_best.pt \
        --manifest data/processed/land/manifest.json \
        --cache-dir data/processed/land/cache \
        --out-dir data/processed/land/latents

Output: <out-dir>/<patient_id>.npz per patient, with arrays:
    "latent" -- float32, (latent_channels, 64, 64, 64). The posterior MEAN (not sampled) --
                a fixed, reproducible input to diffusion training for the same VAE weights.
    "mask"   -- float32, (64, 64, 64). Same downsample_mask_maxpool(factor=4) call the
                VAE-stage dataset applies per-batch -- computed once here since it's a plain,
                cheap function of the already-cached full-res mask.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch

from src.data.lidc_dataset import LIDCSample, load_cached_npz
from src.data.masks import downsample_mask_maxpool
from src.data.sliding_window import sliding_window_average
from src.models.vae import VAE
from src.utils.config import load_config, get_device

# CT-space encoder window: the known-safe patch size established empirically during VAE
# training (96^3 clears the ~2.8GB conv1 workspace comfortably on an 8GB card; 128^3 hits a
# conv2 fragmentation OOM that was never confirmed fixed -- see docs/06_open_questions.md).
# Reusing 96^3 here means every window this script encodes is something already known to fit.
CT_PATCH_SIZE = 96
MASK_DOWNSAMPLE_FACTOR = 4   # matches configs/data_config.yaml mask_encoding.mask_downsample_factor

# Latent-space window derived directly from the CT-space one: 96 / 4 = 24.
LATENT_PATCH_SIZE = CT_PATCH_SIZE // MASK_DOWNSAMPLE_FACTOR   # 24
# 8-voxel overlap in latent space (32-voxel overlap in CT space) -- comfortably within the
# overlap <= patch/2 guard rail in blend_weights_1d (8 <= 12).
LATENT_STRIDE = LATENT_PATCH_SIZE - 8                          # 16


def load_manifest_samples(manifest_path: str, splits: list[str]) -> list[LIDCSample]:
    """
    Real manifest.json format is a dict keyed by split -- {"train": [...], "val": [...],
    "test": [...]} -- NOT a flat list. Reads only the requested splits (default: train + val,
    matching what diffusion training will actually need; test is held out on purpose).
    """
    with open(manifest_path) as f:
        data = json.load(f)
    samples = []
    for split in splits:
        for row in data.get(split, []):
            samples.append(LIDCSample(
                patient_id=row["patient_id"],
                scan_dicom_dir=row["scan_dicom_dir"],
                is_healthy=row["is_healthy"],
                nodule_texture_score=row.get("nodule_texture_score"),
            ))
    return samples


@torch.no_grad()
def encode_full_volume(
    vae: VAE,
    ct: np.ndarray,
    device: str,
    latent_channels: int,
) -> np.ndarray:
    """Encode one full-resolution CT volume to a full 64^3 x latent_channels latent.

    ct: (D, H, W) float32, already HU-windowed/normalized -- the same array
    LIDCVolumeDataset would crop a random 96^3 patch out of; this instead covers the WHOLE
    volume with overlapping 96^3 windows and blends the results.
    """
    latent_shape = tuple(s // MASK_DOWNSAMPLE_FACTOR for s in ct.shape)

    def encode_patch_fn(ld0: int, lh0: int, lw0: int) -> np.ndarray:
        # Latent-space window origin -> CT-space window origin: exact scale-up, since these
        # origins are generated by sliding_window_average operating directly on latent_shape.
        d0, h0, w0 = ld0 * MASK_DOWNSAMPLE_FACTOR, lh0 * MASK_DOWNSAMPLE_FACTOR, lw0 * MASK_DOWNSAMPLE_FACTOR
        ct_patch = ct[d0:d0 + CT_PATCH_SIZE, h0:h0 + CT_PATCH_SIZE, w0:w0 + CT_PATCH_SIZE]
        x = torch.from_numpy(ct_patch[np.newaxis, np.newaxis]).to(device=device, dtype=torch.float32)
        posterior = vae.encode(x)
        z = posterior.mode()   # deterministic -- see module docstring
        return z.squeeze(0).cpu().numpy().astype(np.float32)

    return sliding_window_average(
        volume_shape=latent_shape,
        patch_size=LATENT_PATCH_SIZE,
        stride=LATENT_STRIDE,
        encode_patch_fn=encode_patch_fn,
        out_channels=latent_channels,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--checkpoint", required=True, help="VAE checkpoint, e.g. checkpoints/vae/vae_epoch0084_best.pt")
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--cache-dir", required=True, help="dir of <patient_id>.npz CT+mask caches (VAE-stage)")
    parser.add_argument("--out-dir", required=True, help="dir to write <patient_id>.npz latent+mask caches")
    parser.add_argument("--splits", nargs="+", default=["train", "val"],
                         help="Which manifest splits to precompute latents for (default: train val)")
    parser.add_argument("--vae-config", default="configs/vae_config.yaml")
    parser.add_argument("--data-config", default="configs/data_config.yaml")
    parser.add_argument("--limit", type=int, default=None, help="only process the first N patients (debugging)")
    args = parser.parse_args()

    device = get_device()
    cfg = load_config(vae=args.vae_config, data=args.data_config)
    vae = VAE.from_config(cfg.vae).to(device)

    # Real checkpoints are saved as {"epoch":..., "best_val_loss":..., "vae_state": vae.state_dict()}
    # -- NOT under a "model" key. weights_only=False matches how train_vae.py itself loads checkpoints.
    ckpt = torch.load(args.checkpoint, map_location=device, weights_only=False)
    vae.load_state_dict(ckpt["vae_state"])
    vae.eval()
    print(f"Loaded VAE checkpoint from epoch {ckpt.get('epoch', '?')} "
          f"(best_val_loss={ckpt.get('best_val_loss', float('nan')):.4f}): {args.checkpoint}")

    manifest = load_manifest_samples(args.manifest, args.splits)
    if args.limit:
        manifest = manifest[: args.limit]

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Precomputing latents for {len(manifest)} patients (splits={args.splits}) on {device}")
    print(f"  CT-space window:     {CT_PATCH_SIZE}^3")
    print(f"  Latent-space window: {LATENT_PATCH_SIZE}^3, stride {LATENT_STRIDE} "
          f"(overlap {LATENT_PATCH_SIZE - LATENT_STRIDE})")

    for i, sample in enumerate(manifest):
        out_path = out_dir / f"{sample.patient_id}.npz"
        if out_path.exists():
            print(f"  [{i + 1}/{len(manifest)}] {sample.patient_id}: already cached, skipping")
            continue

        ct, mask = load_cached_npz(sample, args.cache_dir)
        latent = encode_full_volume(
            vae, ct, device, latent_channels=cfg.vae.architecture.latent_channels
        )
        mask_down = downsample_mask_maxpool(mask, factor=MASK_DOWNSAMPLE_FACTOR)

        np.savez_compressed(
            out_path, latent=latent.astype(np.float32), mask=mask_down.astype(np.float32)
        )
        print(
            f"  [{i + 1}/{len(manifest)}] {sample.patient_id}: "
            f"latent {latent.shape}, mask {mask_down.shape} -> {out_path.name}"
        )

    print("Done.")


if __name__ == "__main__":
    main()
